# Generated by Django 5.2.3 on 2025-08-16 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, verbose_name='Domen nomi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('scanning', 'Tahlil qilinmoqda'), ('completed', 'Tugallandi'), ('failed', 'Xatolik')], default='pending', max_length=20, verbose_name='Holat')),
                ('scan_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tahlil sanasi')),
                ('scan_result', models.JSONField(default=dict, verbose_name='Tahlil natijasi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('dns_records', models.JSONField(blank=True, default=dict, verbose_name='DNS yozuvlari')),
                ('ssl_info', models.JSONField(blank=True, default=dict, verbose_name="SSL ma'lumotlari")),
                ('security_headers', models.JSONField(blank=True, default=dict, verbose_name='Xavfsizlik sarlavhalari')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Xatolik xabari')),
            ],
            options={
                'verbose_name': 'Domen tahlili',
                'verbose_name_plural': 'Domen tahlillari',
                'ordering': ['-scan_date'],
                'indexes': [models.Index(fields=['domain_name'], name='scaner_doma_domain__a01e61_idx'), models.Index(fields=['status'], name='scaner_doma_status_b683c8_idx'), models.Index(fields=['scan_date'], name='scaner_doma_scan_da_c4d7cf_idx')],
            },
        ),
    ]
