# Generated by Django 5.2.3 on 2025-08-16 17:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Sessiya nomi')),
                ('domains', models.JSONField(default=list, verbose_name='Domainlar')),
                ('tools', models.JSONField(default=list, verbose_name="Tool'lar")),
                ('status', models.CharField(choices=[('preparing', 'Tayyorlanmoqda'), ('running', 'Ishlayapti'), ('completed', 'Tugallandi'), ('failed', 'Xatolik'), ('cancelled', 'Bekor qilindi')], default='preparing', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan sana')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan sana')),
                ('results', models.JSONField(default=dict, verbose_name='Natijalar')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Xatolik xabari')),
            ],
            options={
                'verbose_name': 'Tahlil Sessiyasi',
                'verbose_name_plural': 'Tahlil Sessiyalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tool nomi')),
                ('tool_type', models.CharField(choices=[('sqlmap', 'SQLMap'), ('nmap', 'Nmap'), ('xsstrike', 'XSStrike'), ('gobuster', 'Gobuster'), ('custom', 'Boshqa')], max_length=20, verbose_name='Tool turi')),
                ('executable_path', models.CharField(max_length=500, verbose_name="Ishlatish yo'li")),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': "Tool'lar",
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='domainscan',
            options={'ordering': ['-scan_date'], 'verbose_name': 'Domain Tahlil', 'verbose_name_plural': 'Domain Tahlillar'},
        ),
        migrations.AlterField(
            model_name='domainscan',
            name='dns_records',
            field=models.JSONField(default=dict, verbose_name='DNS yozuvlari'),
        ),
        migrations.AlterField(
            model_name='domainscan',
            name='domain_name',
            field=models.CharField(max_length=255, verbose_name='Domain nomi'),
        ),
        migrations.AlterField(
            model_name='domainscan',
            name='security_headers',
            field=models.JSONField(default=dict, verbose_name='Xavfsizlik sarlavhalari'),
        ),
        migrations.AlterField(
            model_name='domainscan',
            name='ssl_info',
            field=models.JSONField(default=dict, verbose_name="SSL ma'lumotlari"),
        ),
        migrations.CreateModel(
            name='ToolExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, verbose_name='Domain')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('running', 'Ishlayapti'), ('completed', 'Tugallandi'), ('failed', 'Xatolik')], default='pending', max_length=20, verbose_name='Holat')),
                ('command', models.TextField(verbose_name='Buyruq')),
                ('parameters', models.JSONField(default=dict, verbose_name='Parametrlar')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan sana')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan sana')),
                ('output', models.TextField(blank=True, verbose_name='Natija')),
                ('error_output', models.TextField(blank=True, verbose_name='Xatolik')),
                ('exit_code', models.IntegerField(blank=True, null=True, verbose_name='Chiqish kodi')),
                ('scan_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='scaner.scansession', verbose_name='Tahlil sessiyasi')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scaner.tool', verbose_name='Tool')),
            ],
            options={
                'verbose_name': 'Tool Ishga tushirish',
                'verbose_name_plural': 'Tool Ishga tushirishlar',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Parametr nomi')),
                ('short_name', models.CharField(blank=True, max_length=20, verbose_name='Qisqa nom')),
                ('parameter_type', models.CharField(choices=[('flag', 'Bayroq'), ('option', 'Variant'), ('input', 'Kiritish'), ('checkbox', 'Belgilash')], max_length=20, verbose_name='Parametr turi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('default_value', models.CharField(blank=True, max_length=255, verbose_name='Standart qiymat')),
                ('is_required', models.BooleanField(default=False, verbose_name='Majburiy')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='scaner.tool', verbose_name='Tool')),
            ],
            options={
                'verbose_name': 'Tool Parametri',
                'verbose_name_plural': 'Tool Parametrlari',
                'ordering': ['tool', 'order'],
            },
        ),
    ]
