# Generated by Django 5.2.3 on 2025-08-19 09:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaner', '0002_scansession_tool_alter_domainscan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeshDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, unique=True, verbose_name='Domain nomi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Hesh Domain',
                'verbose_name_plural': 'Hesh Domainlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain_name'], name='scaner_hesh_domain__a9d9f0_idx'), models.Index(fields=['created_at'], name='scaner_hesh_created_61bbb4_idx'), models.Index(fields=['is_active'], name='scaner_hesh_is_acti_feee89_idx')],
            },
        ),
    ]
