# Generated by Django 5.2.3 on 2025-08-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaner', '0003_heshdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeshDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, unique=True, verbose_name='Domain nomi')),
            ],
            options={
                'verbose_name': 'Kesh Domain',
                'verbose_name_plural': 'Kesh Domainlar',
                'ordering': ['domain_name'],
            },
        ),
        migrations.DeleteModel(
            name='HeshDomain',
        ),
        migrations.AddIndex(
            model_name='keshdomain',
            index=models.Index(fields=['domain_name'], name='scaner_kesh_domain__b7021d_idx'),
        ),
    ]
