# Generated by Django 5.2.3 on 2025-08-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaner', '0004_keshdomain_delete_heshdomain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keshdomain',
            name='gobuster',
            field=models.TextField(default='gobuster dir -u http://{domain} -w /usr/share/wordlists/dirb/common.txt', verbose_name="Gobuster buyrug'i"),
        ),
        migrations.AddField(
            model_name='keshdomain',
            name='nmap',
            field=models.TextField(default='nmap -sS -sV -O -p- {domain}', verbose_name="Nmap buyrug'i"),
        ),
        migrations.AddField(
            model_name='keshdomain',
            name='sqlmap',
            field=models.TextField(default='sqlmap -u http://{domain} --batch --random-agent', verbose_name="SQLMap buyrug'i"),
        ),
        migrations.AddField(
            model_name='keshdomain',
            name='xsstrike',
            field=models.TextField(default='python xsstrike.py -u http://{domain} --skip-dom', verbose_name="XSStrike buyrug'i"),
        ),
    ]
