# Generated by Django 5.2.3 on 2025-08-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaner', '0004_keshdomain_delete_heshdomain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keshdomain',
            name='tool_commands',
            field=models.JSONField(default=list, help_text="Tool va buyruqlar ro'yxati", verbose_name='Tool buyruqlari'),
        ),
    ]
