# Generated by Django 5.2.3 on 2025-08-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaner', '0005_update_keshdomain_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keshdomain',
            name='gobuster',
            field=models.TextField(default='gobuster dir -u https://{domain} -w common.txt', verbose_name="Gobuster buyrug'i"),
        ),
        migrations.AlterField(
            model_name='keshdomain',
            name='nmap',
            field=models.TextField(default='nmap {domain}', verbose_name="Nmap buyrug'i"),
        ),
        migrations.AlterField(
            model_name='keshdomain',
            name='sqlmap',
            field=models.TextField(default='sqlmap -u https://{domain}', verbose_name="SQLMap buyrug'i"),
        ),
        migrations.AlterField(
            model_name='keshdomain',
            name='xsstrike',
            field=models.TextField(default='xsstrike -u https://{domain}', verbose_name="XSStrike buyrug'i"),
        ),
    ]
