# Generated by Django 5.2.3 on 2025-08-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaner', '0006_update_keshdomain_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='keshdomain',
            name='gobuster_params',
            field=models.JSONField(default=list, verbose_name='Gobuster parametrlari'),
        ),
        migrations.AddField(
            model_name='keshdomain',
            name='nmap_params',
            field=models.JSONField(default=list, verbose_name='Nmap parametrlari'),
        ),
        migrations.AddField(
            model_name='keshdomain',
            name='sqlmap_params',
            field=models.JSONField(default=list, verbose_name='SQLMap parametrlari'),
        ),
        migrations.AddField(
            model_name='keshdomain',
            name='xsstrike_params',
            field=models.JSONField(default=list, verbose_name='XSStrike parametrlari'),
        ),
    ]
