# Generated by Django 5.2.3 on 2025-08-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaner', '0007_keshdomain_gobuster_params_keshdomain_nmap_params_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keshdomain',
            name='gobuster',
        ),
        migrations.RemoveField(
            model_name='keshdomain',
            name='gobuster_params',
        ),
        migrations.RemoveField(
            model_name='keshdomain',
            name='nmap',
        ),
        migrations.RemoveField(
            model_name='keshdomain',
            name='nmap_params',
        ),
        migrations.RemoveField(
            model_name='keshdomain',
            name='sqlmap',
        ),
        migrations.RemoveField(
            model_name='keshdomain',
            name='sqlmap_params',
        ),
        migrations.RemoveField(
            model_name='keshdomain',
            name='xsstrike',
        ),
        migrations.RemoveField(
            model_name='keshdomain',
            name='xsstrike_params',
        ),
        migrations.AddField(
            model_name='keshdomain',
            name='tool_commands',
            field=models.JSONField(default=list, help_text="Tool va buyruqlar ro'yxati", verbose_name='Tool buyruqlari'),
        ),
    ]
