# Generated by Django 5.2.3 on 2025-08-21 05:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaner', '0008_remove_keshdomain_gobuster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainToolConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(max_length=50, verbose_name='Tool turi')),
                ('base_command', models.TextField(verbose_name='Asosiy buyruq')),
                ('selected_parameters', models.JSONField(default=list, verbose_name='Tanlangan parametrlar')),
                ('final_command', models.TextField(verbose_name='Yakuniy buyruq')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Domain Tool Konfiguratsiyasi',
                'verbose_name_plural': 'Domain Tool Konfiguratsiyalari',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='keshdomain',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Kesh Domain', 'verbose_name_plural': 'Kesh Domainlar'},
        ),
        migrations.AddField(
            model_name='keshdomain',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana'),
        ),
        migrations.AddField(
            model_name='keshdomain',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='keshdomain',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AddIndex(
            model_name='keshdomain',
            index=models.Index(fields=['is_active'], name='scaner_kesh_is_acti_91f342_idx'),
        ),
        migrations.AddIndex(
            model_name='keshdomain',
            index=models.Index(fields=['updated_at'], name='scaner_kesh_updated_d4d645_idx'),
        ),
        migrations.AddField(
            model_name='domaintoolconfiguration',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_configs', to='scaner.keshdomain', verbose_name='Domain'),
        ),
        migrations.AlterUniqueTogether(
            name='domaintoolconfiguration',
            unique_together={('domain', 'tool_type')},
        ),
    ]
