# Generated by Django 5.2.3 on 2025-08-22 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scaner', '0009_domaintoolconfiguration_alter_keshdomain_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scansession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Skan Sessiyasi', 'verbose_name_plural': 'Skan Sessiyalari'},
        ),
        migrations.RemoveField(
            model_name='scansession',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='scansession',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='scansession',
            name='name',
        ),
        migrations.RemoveField(
            model_name='scansession',
            name='results',
        ),
        migrations.RemoveField(
            model_name='scansession',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='scansession',
            name='status',
        ),
        migrations.RemoveField(
            model_name='scansession',
            name='tools',
        ),
        migrations.DeleteModel(
            name='ToolExecution',
        ),
    ]
