# Generated by Django 5.2.3 on 2025-08-22 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaner', '0010_alter_scansession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolparameter',
            name='help_text',
            field=models.TextField(blank=True, verbose_name='Yordam matni'),
        ),
        migrations.AddField(
            model_name='toolparameter',
            name='placeholder',
            field=models.CharField(blank=True, max_length=255, verbose_name='Placeholder matni'),
        ),
        migrations.AddField(
            model_name='toolparameter',
            name='validation_regex',
            field=models.CharField(blank=True, max_length=255, verbose_name='Validatsiya regex'),
        ),
        migrations.AlterField(
            model_name='toolparameter',
            name='parameter_type',
            field=models.CharField(choices=[('flag', 'Bayroq (--help)'), ('option', 'Variant (--level 1)'), ('input', 'Kiritish (--url https://...'), ('checkbox', 'Belgilash (--verbose)')], max_length=20, verbose_name='Parametr turi'),
        ),
        migrations.CreateModel(
            name='ToolParameterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=500, verbose_name='Qiymat')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Faollashtirilgan')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='scaner.keshdomain', verbose_name='Domain')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='scaner.toolparameter', verbose_name='Parametr')),
            ],
            options={
                'verbose_name': 'Tool Parametr Qiymati',
                'verbose_name_plural': 'Tool Parametr Qiymatlari',
                'ordering': ['parameter__order'],
                'unique_together': {('domain', 'parameter')},
            },
        ),
    ]
