# Generated by Django 5.2.3 on 2025-08-24 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaner', '0011_toolparameter_help_text_toolparameter_placeholder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolparameter',
            name='help_text',
        ),
        migrations.RemoveField(
            model_name='toolparameter',
            name='placeholder',
        ),
        migrations.RemoveField(
            model_name='toolparameter',
            name='validation_regex',
        ),
        migrations.AlterField(
            model_name='toolparameter',
            name='parameter_type',
            field=models.CharField(choices=[('flag', 'Bayroq'), ('option', 'Variant'), ('input', 'Kiritish'), ('checkbox', 'Belgilash')], max_length=20, verbose_name='Parametr turi'),
        ),
        migrations.CreateModel(
            name='ToolScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(max_length=50)),
                ('tool_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('running', 'Jarayonda'), ('completed', 'Tugallandi'), ('failed', 'Xatolik')], default='pending', max_length=20)),
                ('command', models.TextField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(default=0.0)),
                ('domain_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_results', to='scaner.domainscan')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.DeleteModel(
            name='ToolParameterValue',
        ),
    ]
