# Generated by Django 5.2.3 on 2025-08-24 17:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaner', '0012_remove_toolparameter_help_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainscan',
            name='current_tool',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Joriy tool'),
        ),
        migrations.AddField(
            model_name='domainscan',
            name='scan_progress',
            field=models.IntegerField(default=0, verbose_name='Tahlil progressi (%)'),
        ),
        migrations.AddField(
            model_name='domainscan',
            name='tool_results',
            field=models.JSONField(default=dict, verbose_name='Tool natijalari'),
        ),
        migrations.CreateModel(
            name='ToolExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=50, verbose_name='Tool nomi')),
                ('tool_type', models.CharField(max_length=50, verbose_name='Tool turi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('running', 'Jarayonda'), ('completed', 'Tugallandi'), ('failed', 'Xatolik')], default='pending', max_length=20, verbose_name='Holat')),
                ('command', models.TextField(verbose_name='Bajarilgan buyruq')),
                ('output', models.TextField(blank=True, verbose_name='Natija')),
                ('error_output', models.TextField(blank=True, verbose_name='Xatolik natijasi')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish vaqti')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Davomiyligi (soniya)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana')),
                ('domain_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='scaner.domainscan', verbose_name='Domain tahlil')),
            ],
            options={
                'verbose_name': 'Tool Bajarilishi',
                'verbose_name_plural': 'Tool Bajarilishlari',
                'ordering': ['-created_at'],
                'unique_together': {('domain_scan', 'tool_name')},
            },
        ),
        migrations.DeleteModel(
            name='ToolScanResult',
        ),
    ]
