# Generated by Django 5.2.3 on 2025-08-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaner', '0013_domainscan_current_tool_domainscan_scan_progress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainscan',
            name='current_tool',
        ),
        migrations.RemoveField(
            model_name='domainscan',
            name='scan_progress',
        ),
        migrations.AlterField(
            model_name='domainscan',
            name='tool_results',
            field=models.JSONField(default=dict, verbose_name='Tool tahlil natijalari'),
        ),
        migrations.DeleteModel(
            name='ToolExecution',
        ),
    ]
