# Generated by Django 5.2.3 on 2025-08-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaner', '0014_remove_domainscan_current_tool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainscan',
            name='raw_tool_output',
            field=models.JSONField(default=dict, verbose_name='Tool raw natijalari'),
        ),
    ]
