# Generated by Django 5.2.3 on 2025-08-25 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaner', '0015_domainscan_raw_tool_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, verbose_name='Domain nomi')),
                ('tool_type', models.CharField(max_length=50, verbose_name='Tool turi')),
                ('process_id', models.IntegerField(blank=True, null=True, verbose_name='Process ID')),
                ('status', models.CharField(choices=[('running', 'Ishlayapti'), ('completed', 'Tugallandi'), ('failed', 'Xatolik'), ('stopped', "To'xtatildi")], default='running', max_length=20)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlash vaqti')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti')),
                ('output_buffer', models.TextField(default='', verbose_name='Output buffer')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Xatolik xabari')),
            ],
            options={
                'verbose_name': 'Scan Process',
                'verbose_name_plural': 'Scan Processes',
                'ordering': ['-start_time'],
                'unique_together': {('domain_name', 'tool_type')},
            },
        ),
    ]
