# Generated by Django 5.2.3 on 2025-08-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scaner', '0016_scanprocess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScanProcess',
        ),
    ]
