# Generated by Django 5.2.3 on 2025-08-29 18:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaner', '0017_delete_scanprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanProcess',
            fields=[
                ('scan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=255)),
                ('tool_type', models.CharField(max_length=50)),
                ('pid', models.IntegerField()),
                ('command', models.TextField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('process_info', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Scan Process',
                'verbose_name_plural': 'Scan Processes',
                'db_table': 'scan_processes',
                'indexes': [models.Index(fields=['domain_name', 'tool_type'], name='scan_proces_domain__5c77ac_idx'), models.Index(fields=['status'], name='scan_proces_status_e21455_idx'), models.Index(fields=['start_time'], name='scan_proces_start_t_9002ee_idx')],
            },
        ),
    ]
