# Generated by Django 5.2.3 on 2025-09-01 00:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaner', '0018_scanprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domains', models.JSONField(default=list, verbose_name='Domainlar')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Diagram',
                'verbose_name_plural': 'Diagrams',
                'ordering': ['-created_at'],
            },
        ),
        # ScanProcess jadvali mavjud emas, shuning uchun o'chirilmaydi
        # migrations.DeleteModel(
        #     name='ScanProcess',
        # ),
    ]
