# Generated by Django 5.2.3 on 2025-08-31 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaner', '0018_scanprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domains', models.JSONField(default=list, verbose_name='Domainlar')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processes',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ScanProcess',
        ),
    ]
